= 2D Pong

==Details

* build with C++11 using modern OpenGL
* using SDL2 for cross-platform (Windows, Linux, OS X)

== Getting the code

* clone the repository recursively (to also pull down the dependencies)

[source, bash]
----
git clone --recursive https://github.com/shearer12345/2d_pong.git
----

* OR fork the repository on github and clone it from your repository

== Building

* Using https://premake.github.io/index.html[premake5] to build the solution and project
  ** Visual Studio 2005, 2008, 2010, 2012, 2013, 2015
  ** Make
  ** Xcode4
  ** MonoDevelop

=== Create the project files

.Windows
[source, bat]
----
./premake5.bat %ACTION% # <1> <2> <3>
----

.Linux, OS X
[source, bash]
----
./premake5 $ACTION # <1> <2> <3>
----

<1> replace `ACTION` with the tool you wish to use - e.g. `vs2015` or `gmake`
<2> uses the project specification given in the `premake5.lua` file. Have a look at it if you're interested.
<3> try `premake5 --help` for the options

=== Build the project

==== Visual Studio

1. Load the `.sln` file
2. Build and run the project you wish to explore - kbd:[F5]

  ** if there are multiple projects, btn:[right-click] and select `make active project` to make that project build/run by default
  ** you can set the project to debug or release mode in the UI

==== Make

[source, bash]
----
make $EXAMPLE # <1> <2> <3> <4>
./src/$EXAMPLE/$EXAMPLE-debug # <5>
----
<1> replace `EXAMPLE` with the example you wish to run
<2> compile and link project `EXAMPLE`.
<3> running just `make` will build all projects
<4> use `make $EXAMPLE config=release` to build for release mode
<5> run `EXAMPLE`. Strip off `-debug` for release builds


== Licensing

* the source code is MIT licensed (see link:LICENSE[LICENSE])
